name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.15.1'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint code
        run: npm run lint

      - name: Build application
        run: npm run build

      # You no longer need an export step, as this is handled in the build
